[package]
name = "yeokja-parser-myst"
version = "0.1.0"
edition = "2024"

[dependencies]
yeokja-core = { path = "../core" }
yeokja-parser-utils = { path = "../parser-utils" }
yeokja-parser-markdown-dialect = { path = "../parser-markdown-dialect" }

[dev-dependencies]
yeokja-parser-markdown = { path = "../parser-markdown" }
