[package]
name = "yeokja-parsers"
version = "0.1.0"
edition = "2024"

[dependencies]
glob = "0.3"
yeokja-core = { path = "../core" }
yeokja-parser-markdown = { path = "../parser-markdown" }
yeokja-parser-asciidoc = { path = "../parser-asciidoc" }
yeokja-parser-rst = { path = "../parser-rst" }
yeokja-parser-latex = { path = "../parser-latex" }
yeokja-parser-verso = { path = "../parser-verso" }
yeokja-parser-mdx = { path = "../parser-mdx" }
yeokja-parser-myst = { path = "../parser-myst" }
yeokja-parser-markdeep = { path = "../parser-markdeep" }
