[terms."ray tracing"]
translation = "레이 트레이싱"
[terms."ray tracer"]
translation = "레이 트레이서"
[terms."path tracing"]
translation = "경로 추적"
[terms."path tracer"]
translation = "경로 추적기"
[terms."bounding volume hierarchy"]
translation = "경계 볼륨 계층 구조"
[terms."surface normal"]
translation = "표면 법선"
[terms."normal vector"]
translation = "법선 벡터"
[terms."refraction"]
translation = "굴절"
[terms."reflection"]
translation = "반사"
[terms."sampling"]
translation = "샘플링"
[terms."probability density function"]
translation = "확률 밀도 함수"
[terms."viewport"]
translation = "뷰포트"
[terms."diffuse"]
translation = "확산"
[terms."dielectric"]
translation = "유전체"
[terms."Ray Tracing in One Weekend"]
translation = "주말 동안 배우는 레이 트레이싱"
[terms."Ray Tracing: The Next Week"]
translation = "레이 트레이싱: 다음 주"
[terms."Ray Tracing: The Rest of Your Life"]
translation = "레이 트레이싱: 남은 인생"
