"""Translate index display terms once while retaining canonical sort keys and ranges."""
import argparse
from collections import defaultdict, deque
from pathlib import Path
import re
import tomllib

NAMES = {'index': 1, 'indexdef': 1, 'indexfoot': 1, 'indexsee': 2}


def group(text, at):
    while at < len(text) and text[at].isspace():
        at += 1
    if at >= len(text) or text[at] != '{':
        raise ValueError('expected a TeX argument')
    start = at + 1
    depth = 1
    at += 1
    while at < len(text):
        if text[at] == '\\':
            at += 2
            continue
        if text[at] == '%':
            end = text.find('\n', at)
            at = len(text) if end < 0 else end + 1
            continue
        depth += (text[at] == '{') - (text[at] == '}')
        if depth == 0:
            return start, at
        at += 1
    raise ValueError('unclosed TeX argument')


def calls(text, names=NAMES):
    at = 0
    while at < len(text):
        if text[at] == '%':
            end = text.find('\n', at)
            at = len(text) if end < 0 else end + 1
            continue
        if text[at] != '\\':
            at += 1
            continue
        m = re.match(r'\\([a-zA-Z]+)', text[at:])
        if not m:
            at += 2
            continue
        name = m[1]
        at += len(m[0])
        if name not in names:
            continue
        args = []
        for _ in range(names[name]):
            span = group(text, at)
            args.append(span)
            at = span[1] + 1
        yield name, args


def split(text, separator):
    parts = []
    depth = 0
    start = at = 0
    while at < len(text):
        if text[at] in ('\\', '"'):
            at += 2
            continue
        depth += (text[at] == '{') - (text[at] == '}')
        if text[at] == separator and depth == 0:
            parts.append(text[start:at])
            start = at + 1
        at += 1
    parts.append(text[start:])
    return parts


def components(key):
    return [split(level, '@')[-1] for level in split(split(key, '|')[0], '!')]


def localize(key, translations, display_only=False):
    fields = split(key, '|')
    levels = []
    for level in split(fields[0], '!'):
        parts = split(level, '@')
        original = parts[-1]
        translated = translations[original]
        levels.append(translated if display_only else parts[0] + '@' + translated)
    if display_only:
        return '!'.join(levels)
    if len(fields) > 2:
        raise ValueError('multiple unquoted MakeIndex format separators')
    return '!'.join(levels) + (('|' + fields[1]) if len(fields) == 2 else '')


def restore_indices(source, translated, dictionary):
    originals = defaultdict(deque)
    for name, args in calls(source):
        originals[name].append([source[a:b] for a, b in args])
    edits = []
    for name, args in calls(translated):
        if not originals[name]:
            raise ValueError(f'extra translated \\{name} marker')
        keys = originals[name].popleft()
        for i, ((a, b), key) in enumerate(zip(args, keys, strict=True)):
            edits.append((a, b, localize(key, dictionary, name == 'indexsee' and i == 1)))
    if any(originals.values()):
        raise ValueError('translated text has missing index markers')
    for a, b, value in reversed(edits):
        translated = translated[:a] + value + translated[b:]
    return translated


def source_files(project):
    config = tomllib.loads((project / 'yeokja.toml').read_text())
    return sorted({'main.tex'} | {s['pattern'] for s in config['sources'] if s['path'] == 'upstream'})


def terms(project):
    found = set()
    for name in source_files(project):
        text = (project / 'upstream' / name).read_text()
        for _, args in calls(text):
            for a, b in args:
                found.update(components(text[a:b]))
    return sorted(found)


def extract(project):
    path = project / 'index' / 'terms.tex'
    path.parent.mkdir(exist_ok=True)
    path.write_text('% Generated by scripts/index_terms.py extract; do not edit.\n' +
                    ''.join('\\section{' + term + '}\n' for term in terms(project)))


def apply(project, tree):
    original = terms(project)
    text = (project / 'ko-index' / 'terms.tex').read_text()
    translated = [text[a:b] for _, [(a,b)] in calls(text, {'section': 1})]
    if len(original) != len(translated):
        raise ValueError('translated index dictionary does not match the source')
    dictionary = dict(zip(original, translated, strict=True))
    for name in source_files(project):
        source = (project / 'upstream' / name).read_text()
        path = tree / name
        text = path.read_text()
        result = restore_indices(source, text, dictionary)
        if result != text:
            if path.is_symlink():
                path.unlink()
            path.write_text(result)


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('action', choices=['extract', 'apply'])
    parser.add_argument('--project', type=Path, default=Path(__file__).resolve().parents[1])
    parser.add_argument('--tree', type=Path, default=Path.cwd())
    args = parser.parse_args()
    if args.action == 'extract':
        extract(args.project)
    else:
        apply(args.project, args.tree)
